# Generated by Django 5.0.7 on 2024-09-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(default=0),
        ),
    ]
