# Generated by Django 5.0.7 on 2024-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS', '0005_rename_publisher_game_publishers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
