# Generated by Django 5.0.7 on 2024-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS', '0004_remove_game_exclusive_alter_game_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
